dist: trusty
sudo: false

language: java
jdk: openjdk11

before_install:
# https://github.com/travis-ci/travis-ci/issues/8408
# Also interferes with platform-tooling-support-tests expectations
  - unset _JAVA_OPTIONS

notifications:
  email:
    on_success: never
    on_failure: always

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: build
    if: tag IS blank
  - name: publish
    if: tag IS present

jobs:
  include:
    - stage: build
      name: "Build and Test"
      script:
      - ./gradlew check
      
    - stage: publish
      name: "Publish to Bintray"
      script:
      - ./gradlew check
      - ./gradlew :shamir:bintrayUpload
